exercis= read.table("household_power_consumption 2.txt",colClasses=c("character","character",rep("numeric",7)),head=TRUE, sep=";" ,na="?")
dayday=subset(exercis,Date=="1/2/2007"|Date=="2/2/2007")
timeinday=paste(dayday$Date,dayday$Time)
dayday$cal=strptime(timeinday, "%d/%m/%Y %H:%M:%S")
hist(dayday$Global_active_power,main="Global Active Power",col="red", xlab="Global Active Power.Kilowatts")
dev.copy(png,file="project1plot1.png")
dev.off()
